/**
  * 创建侧边栏使您能够：
  - 创建一组有序的文档
  - 为该组的每个文档渲染一个侧边栏
  - 提供下一个/上一个导航

  侧边栏可以从文件系统生成，也可以在此处明确定义。

  创建任意数量的侧边栏。
  */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // 默认情况下，Docusaurus 从 docs 文件夹结构生成侧边栏
  tutorialSidebar: [{ type: "autogenerated", dirName: "." }],

  // 但你可以手动创建侧边栏
  /*
   教程侧边栏：[
     '介绍'，
     '你好'，
     {
       类型：'类别'，
       标签：“教程”，
       项目：['教程基础/创建文档']，
     },
   ],
    */
};

module.exports = sidebars;
